rem @launch "Purpur" "Purpur" "https://api.purpurmc.org/v2/purpur/1.19.4/latest/download" "purpur.jar" "" "nogui" 
    @launch "Purpur" "." "https://api.purpurmc.org/v2/purpur/1.20/latest/download" "purpur.jar" "--add-modules=jdk.incubator.vector" "nogui" 
rem @launch "Mohist" "Mohist" "" "" "--add-exports=java.base/sun.security.util=ALL-UNNAMED --add-opens=java.base/java.util.jar=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED" "launchedWithJava16 nogui"
rem @launch "Geyser" "Geyser--Java-Bedrock" "https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/standalone/target/Geyser.jar" "Geyser.jar" "--add-modules=jdk.incubator.vector" "nogui"
rem @launch "Paper" "Paper" "" "paper.jar"